<robot name="model" xmlns:xacro="http://wiki.ros.org/xacro">
    <gazebo reference="l_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="r_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="b_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="f_wheel">
        <material>Gazebo/Read</material>
    </gazebo>

    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>


        <!-- 传动实现:用于连接控制器与关节 -->
    <xacro:macro name="joint_transmission" params="wheel_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${wheel_name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="base_${wheel_name}_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- 每一个驱动轮都需要配置传动装置 -->
    <xacro:joint_transmission wheel_name="l_wheel"/>
    <xacro:joint_transmission wheel_name="r_wheel"/>

    <!-- 控制器 -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>false</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>falsee</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>150.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>base_l_wheel_joint</leftJoint> <!-- 左轮 -->
            <rightJoint>base_r_wheel_joint</rightJoint> <!-- 右轮 -->
            <wheelSeparation>${wheel_driving_between}</wheelSeparation> <!-- 车轮间距 -->
            <wheelDiameter>${wheel_driving_radius * 2}</wheelDiameter> <!-- 车轮直径 -->
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic> <!-- 运动控制话题 -->
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> <!-- 里程计话题 -->
            <odometrySource>1</odometrySource>
            <publishOdomTF>true</publishOdomTF>
            <robotBaseFrame>base_footprint</robotBaseFrame> <!-- 根坐标系 -->
        </plugin>
    </gazebo>
</robot>
    
