<robot name="model" xmlns:xacro="http://wiki.ros.org/xacro">
    <gazebo reference="l_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="r_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="b_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <gazebo reference="f_wheel">
        <material>Gazebo/Read</material>
    </gazebo>

    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>


        <!-- joint_transmission -->
    <xacro:macro name="joint_transmission" params="wheel_name">
        <!-- Transmission is important to link the joints and the controller -->
        <transmission name="${wheel_name}_transmission">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="base_${wheel_name}_joint">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
            </joint>
            <actuator name="${wheel_name}_motor">
                <hardwareInterface>hardware_interface/VelocityJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <!-- settion transimision for driver wheel  -->
    <xacro:joint_transmission wheel_name="l_wheel"/>
    <xacro:joint_transmission wheel_name="r_wheel"/>

    <!--differential controller -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>false</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>false</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>30.0</updateRate>
            <legacyMode>true</legacyMode>
            <leftJoint>base_l_wheel_joint</leftJoint> <!-- left wheel -->
            <rightJoint>base_r_wheel_joint</rightJoint> <!-- right wheel-->
            <wheelSeparation>${wheel_driving_between}</wheelSeparation> <!-- distance of left and right wheel  -->
            <wheelDiameter>${wheel_driving_radius * 2}</wheelDiameter> <!-- radius * 2 -->
            <broadcastTF>1</broadcastTF>
            <wheelTorque>30</wheelTorque>
            <wheelAcceleration>1.8</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic> <!-- topic for controller-->
            <odometryFrame>odom</odometryFrame> 
            <odometryTopic>odom</odometryTopic> <!-- odmetry topic  -->
            <robotBaseFrame>base_footprint</robotBaseFrame> <!-- base frame -->
        </plugin>
    </gazebo>
</robot>
    
